sudo: required

matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
#        - pip install -e .[tensorflow-cpu]
        - pip install -r requirements.txt

      before_script:
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
        # exit-zero treats all errors as warnings. Texar limits lines to a maximum of 80 chars.
        #- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

      script:
        # units test
        - pytest

    - language: java
      install: true
      jdk: oraclejdk8
      script:
        - gradle assemble
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - language: android
      android:
        components:
          - tools
          - android-28
          - build-tools-28.0.0
#          - sys-img-armeabi-v7a-android-28

        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_script:
          - cd android/Shabda
      script:
          - ./gradlew build connectedCheck

      before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

notifications:
  email:
  - mageswaran1989@gmail.com